services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thepassword
      POSTGRES_DB: webhook_service
    ports:
      - "5432:5432"

  api:
    build: .
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://postgres:thepassword@db:5432/webhook_service?sslmode=disable
      - PORT=8080
      - REDIS_URL=redis:6379
    command: ["/api"]

  worker:
    build: .
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - DB_URL=postgres://postgres:thepassword@db:5432/webhook_service?sslmode=disable
      - REDIS_URL=redis:6379
    command: ["/worker"]

volumes:
  pgdata: